name: Production Build & Release

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Run release script
        run: npm run release

      - name: Sync versions (package.json -> jsr.json)
        run: npm run version
