name: Publish on JSR

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    uses: ./.github/workflows/build.yml

  publish-jsr:
    needs: build-and-release
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Publish package
        run: npx jsr publish
