name: Publish on NPM

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-and-release:
    uses: ./.github/workflows/build.yml

  publish-npm:
    needs: build-and-release
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: https://registry.npmjs.org/

      - name: Publish package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
